spring.application.name=myfirstapp
management.endpoints.web.exposure.include = *
management.info.env.enabled = true

management.endpoints.web.exposure.exclude = health, info
info.app.name = vicky
info.app.description = This is vicky app

#Making custume properties
coach.name = Vicky Raj V
Team.name = victory team

#team.name = vicky small team